name: Check Has Package JSON Update
description: Check whether the package.json file was updated with the latest commit
inputs:
  token:
    description: 'The GitHub Secret Token'
    required: true
outputs:
  has-updated:
    description: 'Whether the package.json file was updated in the latest commit'
  dependencies:
    description: 'Current dependencies and devDependencies'
  previous-dependencies:
    description: 'Dependencies and devDependencies before the last commit'
runs:
  using: node16
  main: lib/index.js
